export const themeData = JSON.parse("{\"encrypt\":{},\"print\":false,\"author\":{\"name\":\"独苏\",\"url\":\"https://whoamis.cf/\"},\"logo\":\"/logo.svg\",\"repo\":\"1scy/DuSuJavaGuide\",\"docsDir\":\"demo/theme-docs/src\",\"locales\":{\"/\":{\"lang\":\"zh-CN\",\"navbarLocales\":{\"langName\":\"简体中文\",\"selectLangAriaLabel\":\"选择语言\"},\"metaLocales\":{\"author\":\"作者\",\"date\":\"写作日期\",\"origin\":\"原创\",\"views\":\"访问量\",\"category\":\"分类\",\"tag\":\"标签\",\"readingTime\":\"阅读时间\",\"words\":\"字数\",\"toc\":\"此页内容\",\"prev\":\"上一页\",\"next\":\"下一页\",\"lastUpdated\":\"上次编辑于\",\"contributors\":\"贡献者\",\"editLink\":\"编辑此页\",\"print\":\"打印\"},\"outlookLocales\":{\"themeColor\":\"主题色\",\"darkmode\":\"外观\",\"fullscreen\":\"全屏\"},\"encryptLocales\":{\"iconLabel\":\"文章已加密\",\"placeholder\":\"输入密码\",\"remember\":\"记住密码\",\"errorHint\":\"请输入正确的密码\"},\"routeLocales\":{\"skipToContent\":\"跳至主要內容\",\"notFoundTitle\":\"页面不存在\",\"notFoundMsg\":[\"这里什么也没有\",\"我们是怎么来到这儿的？\",\"这 是 四 零 四 !\",\"看起来你访问了一个失效的链接\"],\"back\":\"返回上一页\",\"home\":\"带我回家\",\"openInNewWindow\":\"Open in new window\"},\"navbar\":[{\"text\":\"主页\",\"icon\":\"home\",\"link\":\"/\"},{\"text\":\"技术书籍\",\"icon\":\"autumn\",\"link\":\"/books/\"},{\"text\":\"面试指南\",\"icon\":\"java\",\"children\":[{\"text\":\"Java\",\"prefix\":\"/java/\",\"children\":[{\"text\":\"基础\",\"link\":\"java-basis.md\"},{\"text\":\"集合\",\"link\":\"java-collection.md\"},{\"text\":\"并发\",\"link\":\"java-concurrent.md\"},{\"text\":\"JVM\",\"link\":\"jvm.md\"},{\"text\":\"Java8\",\"link\":\"java8.md\"}]},{\"text\":\"框架\",\"prefix\":\"/framework/\",\"children\":[{\"text\":\"Spring面试题\",\"link\":\"spring.md\"},{\"text\":\"SpringMVC面试题\",\"link\":\"springmvc.md\"},{\"text\":\"Mybatis面试题\",\"link\":\"mybatis.md\"},{\"text\":\"SpringBoot面试题\",\"link\":\"springboot.md\"},{\"text\":\"SpringCloud详解\",\"link\":\"springcloud.md\"},{\"text\":\"SpringCloud面试题\",\"link\":\"springcloud-interview.md\"},{\"text\":\"Netty详解\",\"link\":\"netty.md\"}]},{\"text\":\"消息队列\",\"prefix\":\"/message-queue/\",\"children\":[{\"text\":\"消息队列面试题\",\"link\":\"mq.md\"},{\"text\":\"RabbitMQ面试题\",\"link\":\"rabbitmq.md\"},{\"text\":\"Kafka面试题\",\"link\":\"kafka.md\"}]},{\"text\":\"关系型数据库\",\"prefix\":\"/database/\",\"children\":[{\"text\":\"MySQL基础\",\"link\":\"mysql-basic.md\"},{\"text\":\"MySQL面试题\",\"link\":\"mysql.md\"},{\"text\":\"MySQL执行计划详解\",\"link\":\"mysql-execution-plan.md\"}]},{\"text\":\"非关系型数据库\",\"prefix\":\"/redis/\",\"children\":[{\"text\":\"Redis基础\",\"link\":\"redis-basic.md\"},{\"text\":\"Redis面试题\",\"link\":\"redis.md\"},{\"text\":\"ElasticSearch面试题\",\"link\":\"elasticsearch.md\"}]}]}],\"sidebar\":{\"/books/\":\"structure\"},\"pageInfo\":[\"Author\",\"Category\",\"Tag\",\"Date\",\"Original\",\"Word\",\"ReadingTime\"],\"footer\":\"默认页脚\",\"displayFooter\":true}}}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updateThemeData) {
    __VUE_HMR_RUNTIME__.updateThemeData(themeData)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ themeData }) => {
    __VUE_HMR_RUNTIME__.updateThemeData(themeData)
  })
}
